import { createHash } from "node:crypto";
import { mkdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";

import type { FileChange, PatchSet, PlanItem } from "../core/index.js";
import type { ApplyArtifact, ApplyPlanOptions, PatchRecipeResult, PlanSelectionResult } from "./types.js";

import { isGeneratedPath, isIgnoredPath, isPathAllowed, normalizeRelativePath } from "../project/index.js";

const CONTENT_HASH_ALGORITHM = "sha256";
const ID_HASH_LENGTH = 12;
const README_PATH = "README.md";

function countLines(value: string): number {
  if (value.length === 0) {
    return 0;
  }

  return value.split("\n").length;
}

function createHashId(prefix: string, values: readonly string[]): string {
  const hash = createHash(CONTENT_HASH_ALGORITHM).update(values.join(":")).digest("hex").slice(0, ID_HASH_LENGTH);

  return `${prefix}-${hash}`;
}

function createPatchSet(runId: string, planItem: PlanItem, result: PatchRecipeResult): PatchSet {
  return {
    changes: result.changes,
    id: createHashId("patch-set", [runId, planItem.id]),
    planItemId: planItem.id,
    runId,
    status: result.status,
    summary: result.summary
  };
}

function createReadmeContent(options: ApplyPlanOptions): string {
  const { inventory } = options;
  const installCommand =
    inventory.project.packageManager === "unknown" ? "Install dependencies with the project package manager." : `${inventory.project.packageManager} install`;
  const checkLines =
    inventory.checkGuards.length === 0
      ? ["- No check guards are configured yet."]
      : inventory.checkGuards.map((checkGuard) => `- \`${checkGuard.command}\``);

  return [
    `# ${inventory.project.name}`,
    "",
    "## Setup",
    "",
    `- ${installCommand}`,
    "",
    "## Verification",
    "",
    "Run the configured project checks:",
    "",
    ...checkLines,
    "",
    "## Development Notes",
    "",
    "This README is a starting point generated by Pimp My Codebase Agent. Replace it with project-specific setup, architecture, and workflow notes as the project evolves.",
    ""
  ].join("\n");
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Apply mode checks a validated target path before writing.
    await stat(filePath);
    return true;
  } catch {
    return false;
  }
}

function getRelativeTargetError(options: ApplyPlanOptions, relativePath: string): string | undefined {
  const normalizedPath = normalizeRelativePath(relativePath);
  const resolvedRoot = path.resolve(options.inventory.project.rootPath);
  const resolvedTarget = path.resolve(resolvedRoot, normalizedPath);

  if (resolvedTarget !== resolvedRoot && !resolvedTarget.startsWith(`${resolvedRoot}${path.sep}`)) {
    return `${normalizedPath} is outside the project root.`;
  }

  if (isIgnoredPath(normalizedPath, options.config.privacy.ignore)) {
    return `${normalizedPath} is ignored by privacy config.`;
  }

  if (isGeneratedPath(normalizedPath) && !isPathAllowed(normalizedPath, options.config.generatedFileAllowlist)) {
    return `${normalizedPath} is generated and not allowlisted.`;
  }

  return undefined;
}

function getSelectedItems(options: ApplyPlanOptions): PlanSelectionResult {
  const selectedItems: PlanItem[] = [];
  const errors: string[] = [];
  const selectedItemIdSet = new Set(options.selectedItemIds);

  if (options.selectedItemIds.length === 0) {
    errors.push("At least one plan item ID must be selected with --items.");
  }

  for (const itemId of selectedItemIdSet) {
    const planItem = options.planArtifact.plan.items.find((item) => item.id === itemId);

    if (planItem === undefined) {
      errors.push(`Selected plan item '${itemId}' was not found in the plan.`);
      continue;
    }

    if (planItem.risk === "high" && !options.allowHighRisk) {
      errors.push(`Selected plan item '${itemId}' is high risk. Pass --allow-high-risk to apply it.`);
      continue;
    }

    selectedItems.push(planItem);
  }

  return {
    errors,
    selectedItems
  };
}

function incrementStatusCount(counts: Map<string, number>, patchSet: PatchSet): void {
  counts.set(patchSet.status, (counts.get(patchSet.status) ?? 0) + 1);
}

async function applyDocumentationRecipe(options: ApplyPlanOptions, planItem: PlanItem): Promise<PatchRecipeResult> {
  const targetError = getRelativeTargetError(options, README_PATH);

  if (targetError !== undefined) {
    return {
      changes: [],
      status: "failed",
      summary: targetError
    };
  }

  const targetPath = path.join(options.inventory.project.rootPath, README_PATH);

  if (await fileExists(targetPath)) {
    return {
      changes: [],
      status: "skipped",
      summary: `${README_PATH} already exists; apply mode refused to overwrite it.`
    };
  }

  const content = createReadmeContent(options);

  // eslint-disable-next-line security/detect-non-literal-fs-filename -- Apply mode writes a fixed safe root README target after path validation.
  await mkdir(path.dirname(targetPath), { recursive: true });
  // eslint-disable-next-line security/detect-non-literal-fs-filename -- Apply mode writes a fixed safe root README target after path validation.
  await writeFile(targetPath, content, "utf8");

  const patchSetId = createHashId("patch-set", [options.runId, planItem.id]);
  const change: FileChange = {
    changeType: "create",
    id: createHashId("file-change", [patchSetId, README_PATH]),
    linesAdded: countLines(content),
    linesRemoved: 0,
    patchSetId,
    path: README_PATH
  };

  return {
    changes: [change],
    status: "applied",
    summary: `Created ${README_PATH} with setup and verification starter notes.`
  };
}

async function applyPlanItem(options: ApplyPlanOptions, planItem: PlanItem): Promise<PatchSet> {
  if (planItem.category === "documentation") {
    return createPatchSet(options.runId, planItem, await applyDocumentationRecipe(options, planItem));
  }

  return createPatchSet(options.runId, planItem, {
    changes: [],
    status: "skipped",
    summary: `No safe apply recipe exists yet for ${planItem.category} plan items.`
  });
}

function summarizePatchSets(runId: string, patchSets: readonly PatchSet[]): ApplyArtifact {
  const byStatus = new Map<string, number>();
  const changedFiles = new Set<string>();

  for (const patchSet of patchSets) {
    incrementStatusCount(byStatus, patchSet);

    for (const change of patchSet.changes) {
      changedFiles.add(change.path);
    }
  }

  return {
    patchSets,
    runId,
    summary: {
      byStatus: Object.fromEntries(byStatus),
      changedFiles: changedFiles.size,
      total: patchSets.length
    }
  };
}

export async function applyPlan(options: ApplyPlanOptions): Promise<ApplyArtifact> {
  const selection = getSelectedItems(options);

  if (selection.errors.length > 0) {
    throw new Error(selection.errors.join(" "));
  }

  const patchSets: PatchSet[] = [];

  for (const planItem of selection.selectedItems) {
    patchSets.push(await applyPlanItem(options, planItem));
  }

  return summarizePatchSets(options.runId, patchSets);
}
